SecureDev/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.SqlClient;
using System.Data.SQLite;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Vladi2.Models;
using System.Web.Script.Serialization;
using System.Web.Security.AntiXss;

namespace Vladi2.Controllers
{
    public class HomeController : BaseController
    {
        // The main application page
        public ActionResult Index()
        {
            return View();
        }

        // Returns json of the searched pet name
        [HttpGet]
        public ActionResult Search(String name)
        {
            string XSSName = AntiXssEncoder.HtmlEncode(name, true);
            var connectionString = ConfigurationManager.ConnectionStrings["SQLiteConnection"].ConnectionString;
            List<Pet> pets = new List<Pet>();
            Pet pet;
            using (var m_dbConnection = new SQLiteConnection(connectionString))
            {
                m_dbConnection.Open();
                SQLiteCommand command = new SQLiteCommand("SELECT * FROM tblpets WHERE petName LIKE @petName", m_dbConnection);
                command.Parameters.AddWithValue("@petName", "%" + XSSName + "%");
                using (SQLiteDataReader reader = command.ExecuteReader())
                {
                    while (reader.Read())
                    {
                        pet = new Pet();
                        // adding messages to the list
                        pet.PetID = int.Parse(AntiXssEncoder.HtmlEncode(reader.GetInt32(0).ToString(), true));
                        pet.PetName = AntiXssEncoder.HtmlEncode(reader.GetString(1).Trim(), true);
                        pet.Price = Decimal.Parse(AntiXssEncoder.HtmlEncode(reader.GetDecimal(2).ToString(), true));
                        pet.PetType = AntiXssEncoder.HtmlEncode(reader.GetString(3).Trim(), true) ;
                        pets.Add(pet);
                    }
                }

                JavaScriptSerializer jss = new JavaScriptSerializer();
                string output = jss.Serialize(pets);
                return Content(output);
            }
        }
    }
}

SecureDev/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.SQLite;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security.AntiXss;
using Vladi2.Models;

namespace Vladi2.Controllers
{
    public class LoginController : BaseController
    {
        // Login page
        // Get the main login page
        public ActionResult Index()
        {
            if (Session["LoggedUserName"] != null)
                return RedirectToAction("Index", "Home");
            return View();
        }

        // Post a login to the application
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(LoginUser u)
        {
            if (Session["LoggedUserName"] != null)
                return RedirectToAction("Index", "Home");

            if (ModelState.IsValid)
            {
                var connectionString = ConfigurationManager.ConnectionStrings["SQLiteConnection"].ConnectionString;
                using (var m_dbConnection = new SQLiteConnection(connectionString))
                {
                    m_dbConnection.Open();
                    SQLiteCommand command = new SQLiteCommand("SELECT * FROM tblusers Where username = @username and password = @password", m_dbConnection);
                    string usernameXSS = AntiXssEncoder.HtmlEncode(u.Username, true);
                    string passwordXSS = AntiXssEncoder.HtmlEncode(u.Password, true);
                    command.Parameters.AddWithValue("@username", usernameXSS);
                    command.Parameters.AddWithValue("@password", passwordXSS);
                    using (SQLiteDataReader reader = command.ExecuteReader())
                    {
                        while (reader.Read())
                        {
                            //if we got here - the select succeded , the user exist in db - redirect to userHome page
                            Session["LoggedUserId"] = reader.GetInt32(0);
                            string userName = reader.GetString(1).Trim();
                            Session["LoggedUserName"] = userName;
                            int isAdmin = reader.GetInt32(8);
                            if (isAdmin == 1)
                                Session["IsAdmin"] = 1;
                            Logging.Log("User " + userName + " has logged in to the system", Logging.AccessType.Valid);
                            return RedirectToAction("Index", "Home");
                        }
                    }
                }
            }
            //the login failed - redirect to login page with the login error

            Logging.Log("A failed login has been attempt with the use of " + u.Username + " credentials", Logging.AccessType.Invalid);
            ViewBag.ErrorMessage = "The username or password are invalid";
            return View(u);
        }

        // Logout from the application
        public ActionResult Logout()
        {
            if(Session["LoggedUserId"] != null)
            {
                Session["LoggedUserId"] = null;
            }

            if(Session["LoggedUserName"] != null)
            {
                Session["LoggedUserName"] = null;
            }
            Session.Abandon();
            return RedirectToAction("Index", "Login");
        }
    }
}

SecureDev/Controllers/RegistrationController.cs
using System;
using System.Collections.Generic;
using System.Data.SQLite;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security.AntiXss;
using Vladi2.Models;

namespace Vladi2.Controllers
{
    public class RegistrationController : BaseController
    {
        // Registration Page
        // Get the main registration page
        public ActionResult Index()
        {
            if (Session["LoggedUserName"] != null)
                return RedirectToAction("Index", "Home");
            return View();
        }

        // Post a new registration
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(User u)
        {
            if (Session["LoggedUserName"] != null)
            {
                Logging.Log("POST REGISTER PAGE : attempt to register user while already logged in", Logging.AccessType.Invalid);
                return RedirectToAction("Index", "Home");
            }
            if (ModelState.IsValid)
            {
                string xssUsername = AntiXssEncoder.HtmlEncode(u.Username, true);
                var connectionString = System.Configuration.ConfigurationManager.ConnectionStrings["SQLiteConnection"].ConnectionString;
                using (var m_dbConnection = new SQLiteConnection(connectionString))
                {
                    m_dbConnection.Open();
                    SQLiteCommand command = new SQLiteCommand("SELECT * FROM tblusers Where username = @username", m_dbConnection);
                    command.Parameters.AddWithValue("@username", xssUsername);
                    using (SQLiteDataReader reader = command.ExecuteReader())
                    {
                        if (reader.HasRows)
                        {
                            Logging.Log("REGISTER PAGE : Attempt to register user with the same username " + xssUsername, Logging.AccessType.Invalid);
                            ViewBag.UserMessage = "Username already exists, please choose a different username";
                            return View();
                        }
                    }
                }
                string fileName = null;
                using (var m_dbConnection = new SQLiteConnection(connectionString))
                {
                    m_dbConnection.Open();
                    SQLiteCommand command = new SQLiteCommand("INSERT INTO tblusers (username, password, firstname, lastname, email, phone, picture, isAdmin) VALUES (@username,@password,@firstname,@lastname,@email,@phone,@picture, 0)", m_dbConnection);
                    command.Parameters.AddWithValue("@username", xssUsername);
                    command.Parameters.AddWithValue("@password", AntiXssEncoder.HtmlEncode(u.Password, true));
                    command.Parameters.AddWithValue("@firstname", AntiXssEncoder.HtmlEncode(u.FirstName, true));
                    command.Parameters.AddWithValue("@lastname", AntiXssEncoder.HtmlEncode(u.LastName, true));
                    command.Parameters.AddWithValue("@email", AntiXssEncoder.HtmlEncode(u.Email, true));
                    command.Parameters.AddWithValue("@phone", AntiXssEncoder.HtmlEncode(u.Phone, true));

                    if (Request.Files.Count > 0 && Request.Files[0].ContentLength > 0 && Request.Files[0].FileName != "")
                    {
                        HttpPostedFileBase pictureFile = Request.Files["Picture"];
                        if (pictureFile.ContentLength > (3 * 1024 * 1024))
                        {
                            Logging.Log("POST : attempt to register user with picture over 3MB " + u.Username, Logging.AccessType.Invalid);
                            ViewBag.PictureMessage = "File size must not exceed 3MB";
                            return View();
                        }
                        
                        string extension = System.IO.Path.GetExtension(pictureFile.FileName);
                        if(extension != ".jpeg" && extension != ".jpg" && extension != ".bmp" && extension != ".gif" && extension != ".tif" && extension != ".png")
                        {
                            Logging.Log("POST : attempt to register user with invalid picture extension " + u.Username, Logging.AccessType.Invalid);
                            ViewBag.PictureMessage = "Please upload a valid file";
                            return View();
                        }
                        string guid = Guid.NewGuid().ToString();
                        //string path = @"C:\Users\K2View\SecureDev\SecureDev_Resources\images\profile\";
                        string path = @"D:\SecureDev\SecureDev_Resources\images\profile\";
                        fileName = System.IO.Path.Combine(path, guid + extension);
                        pictureFile.SaveAs(fileName);
                        fileName = guid + extension;
                    }
                    else
                    {
                        fileName = "default.jpg";
                    }
                    command.Parameters.AddWithValue("@picture", fileName);
                    try
                    {
                        command.ExecuteNonQuery();
                        Logging.Log("POST :Successfuly registered user " + u.Username, Logging.AccessType.Valid);
                    }
                    catch (Exception ex)
                    {
                        throw new Exception(ex.Message);
                    }
                }
                return RedirectToAction("Index", "Information");
            }
            return View();
        }
    }
}

SecureDev/Views/Home/Index.cshtml
@if (Session["LoggedUserName"] != null)
{
    <h2>Welcome @Session["LoggedUserName"].ToString()</h2>
}

@{
    ViewBag.Title = "Home";
}

<div>

</div>
<br />
<div class="panel panel-default">
    <div class="panel-heading">
    Welcome to our wonderful pet store!
    </div>

    <div class="panel-body">
        Here are some of the latest updates : <br/>
        1) We caught some worms and bugs yesterday at the garden - feel free to buy!<br />
        2) New fish are here!!!<br />
    </div>


</div>

<div class="form-group">
    <label class="control-label col-md-1">Search</label>
    <input type="text" class="form-control col-md-7" id="petName" name="name" />
    <div class="col-md-1"></div>
    <input id="submitBtn" type="submit" class="btn btn-primary col-md-2" value="Search" />
</div>
    <br />
    <br />
    <br />
    <div id="petsTable"></div>

    @section scripts {
        <script src="~/scripts/scriptHome.min.js"></script>
    }

SecureDev/Views/Home/Login.cshtml
@model Vladi2.Models.LoginUser

@{
    ViewBag.Title = "Login";
}

<h2>Login</h2>

@using (Html.BeginForm("Login", "Home", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
    <table>
        <tr>
            <td>@Html.LabelFor(a=>a.Username)</td>
            <td>@Html.TextBoxFor(a=>a.Username)</td>
            <td>@Html.ValidationMessageFor(a=>a.Username)</td>
        </tr>
        <tr>
            <td>@Html.LabelFor(a=>a.Password)</td>
            <td>@Html.PasswordFor(a => a.Password)</td>
            <td>@Html.ValidationMessageFor(a => a.Password)</td>
        </tr>
        <tr>
            <td>
                <input type="submit" value="Login" />
            </td>
        </tr>
    </table>
}
<br/>
@Html.ActionLink("Register", "Registration")

SecureDev/Views/Home/Registration.cshtml
@model Vladi2.Models.User

@{
    ViewBag.Title = "Registration";
}

<h2>Registration</h2>

@using (Html.BeginForm("Registration", "Home", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary()

    <fieldset>
        <div>
            @Html.LabelFor(a => a.Username)
        </div>
        <div>
            @Html.EditorFor(a => a.Username)
            @Html.ValidationMessageFor(a => a.Username)
        </div>
        <div>
            @Html.LabelFor(a => a.Password)
        </div>
        <div>
            @Html.EditorFor(a => a.Password)
            @Html.ValidationMessageFor(a => a.Password)
        </div>
        <div>
            @Html.LabelFor(a => a.ComparePassword)
        </div>
        <div>
            @Html.EditorFor(a => a.ComparePassword)
            @Html.ValidationMessageFor(a => a.ComparePassword)
        </div>
        <div>
            @Html.LabelFor(a => a.Email)
        </div>
        <div>
            @Html.EditorFor(a => a.Email)
            @Html.ValidationMessageFor(a => a.Email)
        </div>
        <div>
            @Html.LabelFor(a => a.FirstName)
        </div>
        <div>
            @Html.EditorFor(a => a.FirstName)
            @Html.ValidationMessageFor(a => a.FirstName)
        </div>
        <div>
            @Html.LabelFor(a => a.LastName)
        </div>
        <div>
            @Html.EditorFor(a => a.LastName)
            @Html.ValidationMessageFor(a => a.LastName)
        </div>
        <div>
            @Html.LabelFor(a => a.Phone)
        </div>
        <div>
            @Html.EditorFor(a => a.Phone)
            @Html.ValidationMessageFor(a => a.Phone)
        </div>
        <div>
            @Html.LabelFor(a => a.Picture)
        </div>
        <div>
            @Html.EditorFor(a => a.Picture)
            @Html.ValidationMessageFor(a => a.Picture)
        </div>

        <div>
            <input type="submit" value="Register" />
        </div>
    </fieldset>
}